//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgileESync.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AgileESync.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap direction_1 {
            get {
                object obj = ResourceManager.GetObject("direction-1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap money {
            get {
                object obj = ResourceManager.GetObject("money", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *FLD:Tabela;A;100|Campo;A;100|CampoERP;A;100|Tipo;A;100|Tamanho;A;10|Precisao;A;10
        ///*PKY:Tabela|Campo.
        /// </summary>
        public static string TAB_Campos {
            get {
                return ResourceManager.GetString("TAB_Campos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *FLD:Chave;A;200|Valor;A;200
        ///*PKY:Chave.
        /// </summary>
        public static string TAB_Configuracao {
            get {
                return ResourceManager.GetString("TAB_Configuracao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *FLD:TabelaNome;A;100|CampoNome;A;100|CampoTipo;A;1
        ///*PKY:TabelaNome.
        /// </summary>
        public static string TAB_GatilhoCampos {
            get {
                return ResourceManager.GetString("TAB_GatilhoCampos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *FLD:TabelaNome;A;100|TabelaNomeERP;A;100|GatilhoNome;A;100|GatilhoScript;A;5000
        ///*PKY:TabelaNome.
        /// </summary>
        public static string TAB_Gatilhos {
            get {
                return ResourceManager.GetString("TAB_Gatilhos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *FLD:Nome;A;100|NomeERP;A;100|Query;A;5000|Filtro;A;1000|Ordenacao;A;1000
        ///*PKY:Nome.
        /// </summary>
        public static string TAB_Tabelas {
            get {
                return ResourceManager.GetString("TAB_Tabelas", resourceCulture);
            }
        }
    }
}
